### GENERAL SETTINGS ###

# Site settings
title: CA-935th - Scripps Ranch HS AFJROTC
description: "Welcome to the page for the Scripps Ranch High School AFJROTC. CA-935th.com is run by cadets in our program and serves to showcase our events, cadets, and information about our corps."
baseurl: ""
url: "http://ca-935th.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
#  - title: facebook
#    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 10410 Treena Street,
    - 92131, San Diego,
    - United States.
#email: 
#tel: it's in the contact us page so dont put it here


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Laura Sommers
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Clients information. Shown on Home and About pages.
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."

# Testimonial content. Shown on Home and About page.
#testimonial:
#    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
#    author: Marcel Newman
#    position: WEB DESIGNER - BLACKTIE.CO

