### GENERAL SETTINGS ###

# Site settings
title: "CA-935th - Scripps Ranch HS AFJROTC"
description: "Welcome to the page for the Scripps Ranch High School AFJROTC. CA-935th.com is run by cadets in our program and serves to showcase our events, 
cadets, and information about our corps."
baseurl: ""
url: "http://ca-935th.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
    limit: 9

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/CA-935
  - title: facebook
    url: https://www.facebook.com/srhspublicaffairs
  - title: snapchat-ghost
    url: https://www.snapchat.com/add/srhspa
  - title: youtube-play
    url: https://www.youtube.com/channel/UC13o8MjH8SXrb1QIAHcCEdA
  - title: instagram
    url: https://www.instagram.com/ca.935th

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 10410 Treena Street
    - San Diego, CA 92131
#email: 
#tel: it's in the contact us page so dont put it here


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
#members:
#  - name: Mark Webber
#    position: CEO
#    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#    img: team01.jpg
#    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
#      - title: twitter
#        url: http://twitter.com/handle

members:
  - name: Khushi Chaudhari
    position: Public Affairs Officer
    img: 1315C8A8-F7C3-4539-9B8B-AD1C1185E77C.jpeg
    
  - name: Cassandra Portrey
    position: Public Affairs Asst. Officer in Charge
    img: Cassandra Portrey.JPG
    
  - name: Keshav Srinivasan
    position: Technology Officer in Charge
    img: Keshav Srinivasan.JPG
    
  - name: Sahithi Lingampalli
    position: Technology Asst. Officer in Charge
    img: x.png

  - name: Song-Yeon Kang
    position: Technology NCO
    img: Song-Yeon Kang.JPG
    
alphamembers:
  - name: Jessica Tuey
    position: Alpha Flight Commander
    img: Jessica Tuey.JPG
    social:
      - title: envelope
        url: mailto:abelhurt13@gmail.com
  - name: Racel Ligeralde
    position: Alpha Flight Sergeant
    img: Racel Ligeralde.JPG
    social:
      - title: envelope
        url: mailto:pahel.srivastava@gmail.com
   
bravomembers:
  - name: Hilary Nguyen
    position: Bravo Flight Commander
    img: Hilary Nguyen.JPG
    social:
      - title: envelope
        url: mailto:marcusvelasquez132@gmail.com
  - name: Andres Palacios
    position: Bravo Flight Sergeant
    img: Andres Palacios.JPG
    social:
      - title: envelope
        url: mailto:hkquinn4@gmail.com
    
charliemembers:
  - name: Lucky Hong
    position: Charlie Flight Commander
    img: Lucky Hong .JPG
    social:
      - title: envelope
        url: mailto:ejeffeljohbuan24@gmail.com
  - name: JJ O'Connell
    position: Charlie Flight Sergeant
    img: JJ O'Connell.JPG
    social:
      - title: envelope
        url: mailto:jphamca@yahoo.com

deltamembers:
  - name: Lea Chanthaluxay
    position: Delta Flight Commander
    img: Lea Chanthaluxay.JPG
    social:
      - title: envelope
        url: mailto:j3pag280@gmail.com
  - name: Tyler Hong
    position: Delta Flight Sergeant
    img: Tyler Hong.JPG
    social:
      - title: envelope
        url: mailto:hi.04.nguyen@gmail.com
        
echomembers:
  - name: Annie Lien
    position: Echo Flight Commander
    img: Annie Lien .JPG
    social:
      - title: envelope
        url: mailto:jusnguyen1@gmail.com
  - name: Harini Akurathi
    position: Echo Flight Sergeant
    img: Harini Akurathi.JPG
    social:
      - title: envelope
        url: mailto:michaelhe2016@gmail.com  

foxtrotmembers:
  - name: Christina Nguyen
    position: Foxtrot Flight Commander
    img: Nguyen, Christina 20202021.JPG
    social:
      - title: envelope
        url: mailto:christinan2004@gmail.com
  - name: Lucky Hong
    position: Foxtrot Flight Sergeant
    img: Hong, Lucky 20202021.PNG
    social:
       - title: envelope
         url: mailto:luckyhonglol@gmail.com

golfmembers:
  - name: Ryan Ong
    position: Golf Flight Commander
    img: golfcc1920.jpg
  - name: Rusell Lee
    position: Golf Flight Sergeant
    img: golfsgt1920.jpg

hotelmembers:
  - name: David Udom
    position: Hotel Flight Commander
    img: Udom, David.jpg
  - name: Tom Rufino
    position: Hotel Flight Sergeant
    img: Rufino, Tom.jpg
    
    
armedmembers:
  - name: Xavier Rico
    position: Armed Team Officer in Charge
    img: xavier,rico21-22.JPG
  - name: Silas dela Cruz
    position: Armed Team NCO
    img: x.png

cgmembers:
  - name: Luke Fine
    position: Color Guard Officer in Charge
    img: x.png
  - name: Joylyn Lew
    position: Color Guard NCO
    img: Joylyn Lew.jpg

flagdetailmembers:
  - name: Lea Chanthaluxay
    img: Lea Chanthaluxay.jpg
    position: Flag Detail Officer in Charge
  - name: Manny Monteclar
    position: Flag Detail NCO
    img: Manny Monteclar.jpg

sabermembers:
  - name: Sabella Ibinyopakaka 
    position: Saber Team Officer in Charge
    img: Sabella Ibinyopakaka.jpg
  - name: Jonathan Jiang
    position: Saber Team NCO
    img: Jonathan Jiang.jpg

unarmedmembers:
  - name: Christopher Villalobos
    position: Unarmed Team Officer in Charge
    img: Christopher Villalobos_.jpg
  - name: Akash Pandit
    position: Unarmed Team NCO
    img: x.png


academicmembers:
  - name: Jessica Tuey
    position: Academic Team Officer in Charge
    img: Jessica Tuey.jpg
  - name: Kevin Zhao
    position: Academic Team Asst. Officer in Charge
    img: x.jpg
 
stellarmembers:
  - name: JJ O'Connell
    position: Stellar Xplorers SNCO
    img: JJ O'Connell.jpg
  - name: Andrew Zhang
    position: Stellar Xplorers NCO
    img: Andrew Zhang.JPG 
     
kittyhawkmembers:
  - name: Britney Ton
    position: Kitty Hawk Officer in Charge
    img: Britney Ton.JPG
  - name: Cassandra Portrey
    position: Kitty Hawk Asst. Officer in Charge
    img: Cassandra Portrey.jpg
    
educationmembers:
  - name: Justin Nguyen
    position: Education Officer in Charge
    img: x.png
  - name: Nasiah Burns
    position: Education NCO
    img: x.png
    

staffmembers:
  - name: Jessica Pham
    position: Group Commander
    img: IMG_6095.JPG
    social:
      - title: envelope
        url: mailto:cky2003florida@gmail.com
 
  - name: Christina Nguyen
    position: Deputy Commander
    img: image0.jpg
    social:
      - title: envelope
        url: mailto:samantha.scotchlas@gmail.com
 
  - name: Elijah Bautista
    position: First Sergeant
    img: Elijah Bautista.JPG
    social:
      - title: envelope
        
  - name: Marcus Velasquez
    position: Operations Commander
    img: IMG_6094.JPG
    social:
      - title: envelope
        url: mailto:tkatherine2003@gmail.com
  
  - name: Russell Lee
    position: Mission Support Commander
    img: Russell Lee.JPG
    social:
      - title: envelope
        url: mailto:r.ong40915@gmail.com
  
  - name: Jake Lee
    position: Logistics Commander
    img: Jake Lee.JPG
    social:
      - title: envelope
        url: mailto:jacwub1738@gmail.com
  
  - name: Rutva Mehta
    position: Plans and Programs
    img: Rutva Mehta.jpg
    social:
      - title: envelope
        url: mailto:mackenzietrinh@gmail.com
  
  - name: Khushi Chaudhari
    position: Public Affairs Commander
    img: 1315C8A8-F7C3-4539-9B8B-AD1C1185E77C.jpeg
    social:
      - title: envelope
        url: mailto:justin7354@gmail.com
  
  - name: Tom Rufino
    position: Teams Commander
    img: Tom Rufino.JPG
    social:
      - title: envelope
        url: mailto:derekphan2927@gmail.com

ypfmembers:
  - name: Sabella Ibinyopakaka
    position: YPF Captain
    img: Sabella Ibinyopakaka.JPG
  - name: Maggie Kwee
    position: YPF NCO
    img: Maggie Kwee.JPG 

aptmembers:
  - name: Isabela Canales
    position: APT Officer in Charge
    img: Isabella Canales.JPG
  - name: Kelin Gonzalez
    position: APT NCO
    img: Kelin Gonzalez.JPG

cyberpatriotmembers:
  - name: Jake Lee
    position: CyberPatriot Officer in Charge
    img: Jake Lee.jpg
  - name: Saatvik Aggarwal
    position: CyberPatriot Asst. Officer in Charge
    img: Saatvik Aggarwal.JPG
 

# Clients information. Shown on Home and About pages.
sponsors:
  - name: iD Tech
    img: sponsor1.svg

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Scripps Ranch High Schoolâ€™s Air Force Junior Reserve Officer Training Corps (AFJROTC) CA-935th program has been the number 
one JROTC unit in the San Diego Unified School District for many years. We value hard-work, friendship, and achievement, pushing our 
cadets not only to be their best, but also to perform their best."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "It's not what you have or what you know; it's what you do with your talent, skills, knowledge, and education that will determine your perfomance and give you the competitive edge!"
    author: MSgt. Toledo
    position: Aerospace Science Instructor - SRHS AFJROTC

prose:
  rooturl: '_posts'
  siteurl: 'https://ca-935.github.io'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "tag1"
              value: "tag1"
            - name: "tag2s"
              value: "tag2"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
