### GENERAL SETTINGS ###

# Site settings
title: "CA-935th - Scripps Ranch HS AFJROTC"
description: "Welcome to the page for the Scripps Ranch High School AFJROTC. CA-935th.com is run by cadets in our program and serves to showcase our events, 
cadets, and information about our corps."
baseurl: ""
url: "http://ca-935th.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#8dcced" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
    limit: 9

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/CA-935
  - title: facebook
    url: https://www.facebook.com/srhspublicaffairs
  - title: snapchat-ghost
    url: https://www.snapchat.com/add/srhspa
  - title: youtube-play
    url: https://www.youtube.com/channel/UC13o8MjH8SXrb1QIAHcCEdA
  - title: instagram
    url: https://www.instagram.com/ca.935th

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 10410 Falcon Street
    - San Diego, CA 92131
#email: 
#tel: it's in the contact us page so dont put it here


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
#members:
#  - name: Mark Webber
#    position: CEO
#    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#    img: team01.jpg
#    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
#      - title: twitter
#        url: http://twitter.com/handle

members:
  - name: Morgan Kwee
    position: Public Affairs Officer
    img: Kwee, Morgan25.jpg
    
  - name: Di Nguyen
    position: Public Affairs SNCO
    img: Nguyen, Di25.jpg
    
  - name: Bianca Chan 
    position: Technology Officer in Charge
    img: Chan, Bianca25.jpg
    
  - name: Mithali Bagirthi
    position: Technology NCO
    img: Bagirthi, Mithali25.jpg
    
  - name: Disha Ranjan
    position: Technology NCO
    img: Ranjan, Disha25.jpg

    
 
    
alphamembers: 
  - name: Shayne Maddox
    position: Alpha Flight Commander
    img: Maddox, Shayne25.jpg
    social:
      - title: envelope
        url: mailto:smadman4811@gmail.com
  - name: Haasini Akurathi 
    position: Alpha Flight Sergeant
    img: Akurathi, Haasini25.jpg
    social:
      - title: envelope
        url: mailto:haasini0527@gmail.com 
   
bravomembers:
  - name: Saanvi Iyer
    position: Bravo Flight Commander
    img: Iyer, Saanvi25.jpg
    social:
      - title: envelope
        url: mailto:iyersaanvi20@gmail.com
  - name: Aritri Banerjee
    position: Bravo Flight Sergeant
    img: Banerjee, Aritri25.jpg
    social:
      - title: envelope
        url: mailto:tukkib3009@gmail.com
    
charliemembers:
  - name: Sol Pham
    position: Charlie Flight Commander
    img: Pham, Sol2025.jpg
    social:
      - title: envelope
        url: mailto:ashpham2008@gmail.com
  - name: Kyan Bach
    position: Charlie Flight Sergeant
    img: Bach, Kyan25.jpg
    social:
      - title: envelope
        url: kyan123redpepper@gmail.com

deltamembers:
  - name: Harini Sreeraman
    position: Delta Flight Commander
    img: Sreeraman, Harini25.jpg
    social:
      - title: envelope
        url: mailto:harinis1729@gmail.com
  - name: Chloe Jiang
    position: Delta Flight Sergeant
    img: Jiang, Chloe.jpg
    social:
      - title: envelope
        url: mailto:chloej7749@gmail.com
        
echomembers:
  - name: Noah Beyer
    position: Echo Flight Commander
    img: Beyer, Noah25.jpg
    social:
      - title: envelope
        url: mailto:noahrbeyer@gmail.com
  - name: Zoya Qureshi
    position: Echo Flight Sergeant
    img: Qureshi, Zoya25.jpg
    social:
      - title: envelope
        url: mailto:20zoyaq09@gmail.com

foxtrotmembers:
  - name: Heather Ngo
    position: Foxtrot Flight Commander
    img: Ngo, Heather25.jpg
    social:
      - title: envelope
        url: mailto:heather448448@gmail.com
  - name: Hasini Thamidala
    position: Foxtrot Flight Sergeant
    img: Thamidala, Hasini25.jpg
    social:
       - title: envelope
         url: mailto:hasinit21@gmail.com 

golfmembers:
  - name: Jadelynn Doan
    position: Golf Flight Commander
    img: Doan, Jadelynn25.jpg
    social:
      - title: envelope
        url: mailto:jadelynnd2009@gmail.com
  - name: Ashley Kim
    position: Golf Flight Sergeant
    img: Kim, Ashley25.jpg
    social:
      - title: envelope
        url: mailto:ashleyjkimsd@gmail.com
    
armedmembers:
  - name: Bridge Han
    position: Armed Team Officer in Charge
    img: Han, Bridge25.jpg
  - name: Joseph Tran-Malan
    position: Armed Team NCO
    img: Tran-Malan, Joseph25.jpg

cgmembers:
  - name: David Nasi
    position: Color Guard Officer in Charge
    img: Nasi, David25.jpg
  - name: Chase Hebert
    position: Color Guard NCO
    img: Hebert, Chase25.jpg

flagdetailmembers:
  - name: Maverick Capiendo
    img: Capiendo, Maverick.jpg
    position: Flag Detail Officer in Charge
  - name: Alyssa Ju
    position: Flag Detail NCO
    img: Ju, Alyssa25.jpg

sabermembers:
  - name: Daniel Yang
    position: Saber Team Officer in Charge
    img: Yang, Daniel25.jpg
  - name: Alice Kim
    position: Saber Team NCO
    img: Kim, Alice25.jpg

unarmedmembers:
  - name: Ethan Sim
    position: Unarmed Team Officer in Charge
    img: Sim, Ethan25.jpg
  - name: Arya Deshmukh
    position: Unarmed Team NCO
    img: Deshmukh, Arya25.jpg


academicmembers:
  - name: Kamryn Liu
    position: Academic Team Officer in Charge
    img: Liu, Kamryn25.jpg
  - name: Alyssa Zhou
    position: Academic Team NCO
    img: Zhou, Alyssa25.jpg
 
stellarmembers:
  - name: Heather Ngo
    position: Stellar Xplorers Officer in Charge
    img: Ngo, Heather25.jpg
  - name: Sarah Zheng
    position: Stellar Xplorers NCO
    img: Zheng, Sarah25.jpg

     
kittyhawkmembers:
  - name: Annalisa Boquiren
    position: Kitty Hawk Officer in Charge
    img: Boquiren, Annalisa25.jpg
  - name: Bowie Murthy 
    position: Kitty Hawk Assistant Officer in Charge
    img: Murthy, Bowie25.jpg
  - name: Akshar Udas 
    position: Kitty Hawk NCO
    img: Udas, Akshar25.jpg
    
educationmembers:
  - name: Aryahi Jogi
    position: Education Officer in Charge
    img: Jogi, Aryahi25.jpg
  - name: Samvrutha Ashok
    position: Education NCO
    img: Ashok, Samvrutha25.jpg 
     
    

staffmembers:
  - name: Julia Zou
    position: Group Commander
    img: Zou, Julia25.jpg
    social:
      - title: envelope
        url: mailto:juliazou71@gmail.com
 
  - name: Sonakshi Kanakala
    position: Deputy Commander
    img: Kanakala, Sonakshi25.jpg
    social:
      - title: envelope
        url: mailto:sonakshikanakala@gmail.com
 
  - name: Bella Phan
    position: First Sergeant
    img: Phan, Bella25.jpg
    social:
      - title: envelope
        url: mailto:bellaphan08@gmail.com
        
  - name: Isabella Nguyen
    position: Mission Support Commander
    img: Nguyen, Isabella25.jpg
    social:
      - title: envelope
        url: mailto:isabellanguyen.10.26.2@gmail.com
  
  - name: Hailey Shin
    position: Operations Commander
    img: Shin, Hailey25.jpg
    social:
      - title: envelope
        url: mailto:haileyshin2008@gmail.com
  
  - name: Crystal Hooi
    position: Logistics Commander
    img: Hooi, Crystal25.jpg
    social:
      - title: envelope
        url: mailto:cry.h837@gmail.com 
  
  - name: Yoonah Lee
    position: Plans and Programs Commander
    img: Lee, Yoonah25.jpg
    social:
      - title: envelope
        url: mailto:2808ylee@gmail.com
  
  - name: Morgan Kwee
    position: Public Affairs Commander
    img: Kwee, Morgan25.jpg
    social:
      - title: envelope
        url: mailto:morganjrotc08@gmail.com 
  
  - name: Katherine Kwon
    position: Teams Commander
    img: Kwon, Katherine25.jpg
    social:
      - title: envelope
        url: mailto:kathii.kwon81408@gmail.com

ypfmembers:
  - name: Gael Perez
    position: GPF/YPF Officer
    img: Perez, Gael25.jpg
  - name: Matthew Tran 
    position: GPF NCO
    img: Tran, Matthew25.jpg
  - name: Liu, Olivia
    position: YPF/GPF/Raiders NCO
    img: Liu, Olivia25.jpg

aptmembers:
  - name: Siri Chiruta
    position: APT Officer in Charge
    img: Chiruta, Siri25.jpt
  - name: Kaitlyn Ly
    position: APT Assistant Officer in Charge
    img: Ly, Kaitlyn25.jpt
  - name: Zoya Qureshi
    position: APT NCO
    img: Qureshi, Zoya25.jpg

cyberpatriotmembers:
  - name: Audrey Li
    position: CyberPatriot Officer
    img: Li, Audrey25.JPG
  - name: Arush Sastry
    position: CyberPatriot NCO
    img: 
 

# Clients information. Shown on Home and About pages.
sponsors:
  - name: iD Tech
    img: sponsor1.svg

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Scripps Ranch High School’s Air Force Junior Reserve Officer Training Corps (AFJROTC) CA-935th program has been the number 
one JROTC unit in the San Diego Unified School District for many years. We value hard-work, friendship, and achievement, pushing our 
cadets not only to be their best, but also to perform their best."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "At CA-935, we are forging risk takers.  We are enabling cadets to step outside their comfort zones and venture into the unknown; to learn from their successes and failures without fear of negative consequences. These trials create a common bond, enabling the cadets to trust the process of resilience building. Cadets, we have work to do, the next challenge is coming…."
    author: Major Francis
    position: Senior Aerospace Science Instructor - SRHS AFJROTC

prose:
  rooturl: '_posts'
  siteurl: 'https://ca-935.github.io'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "tag1"
              value: "tag1"
            - name: "tag2s"
              value: "tag2"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
