### GENERAL SETTINGS ###

# Site settings
title: CA-935th - Scripps Ranch HS AFJROTC
description: "Welcome to the page for the Scripps Ranch High School AFJROTC. CA-935th.com is run by cadets in our program and serves to showcase our events, 
cadets, and information about our corps."
baseurl: ""
url: "http://ca-935th.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
    limit: 9

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/CA-935
  - title: facebook
    url: https://www.facebook.com/srhspublicaffairs
  - title: snapchat-ghost
    url: https://www.snapchat.com/add/srhspa
  - title: youtube-play
    url: https://www.youtube.com/channel/UC13o8MjH8SXrb1QIAHcCEdA
  - title: instagram
    url: https://www.instagram.com/srhspa
  - title: list
    url: https://docs.google.com/spreadsheets/d/1UMLIdGYtgGoYcGUewK-46Cc5A2t92IW27aDwlN6YySU/edit?usp=sharing

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 10410 Treena Street
    - San Diego, CA 92131
#email: 
#tel: it's in the contact us page so dont put it here


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
#members:
#  - name: Mark Webber
#    position: CEO
#    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#    img: team01.jpg
#    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
#      - title: twitter
#        url: http://twitter.com/handle
members:
  - name: Lizzie Chavez
    position: Public Affairs Officer
    img: lizzie.jpg
  - name: Brandon Nguyen
    position: Technology NCO
    img: brandon.jpg
    social:
      - title: github
        url: https://github.com/brandonpadres
      - title: gitlab
        url: https://gitlab.com/brandonpadres
  - name: Mitchell Le 
    position: Public Affairs NCO
    img: mitch.jpg
  - name: Thu Vu 
    position: Public Affairs NCO
    img: thu.jpg

armedmembers:
  - name: Anton Phan
    position: Armed Team Commander
    img: commander.jpg
  - name: Jordan Almaas
    position: Armed Team NCO
    img: sergeant.jpg

cgmembers:
  - name: William Rule
    position: Color Guard Commander
    img: commander.jpg
  - name: Marlene Freerksen
    position: Color Guard NCO
    img: sergeant.jpg

flagdetailmembers:
  - name: Mariel Teng II
    position: Flag Detail Commander
    img: commander.jpg
  - name: Julius Bagsic
    position: Flag Detail NCO
    img: sergeant.jpg

sabermembers:
  - name: Jimmy Du 
    position: Saber Team Commander
    img: commander.jpg
  - name: Nick Stone
    position: Saber Team NCO
    img: sergeant.jpg

unarmedmembers:
  - name: Lj Monteclar
    position: Unarmed Team Commander
    img: commander.jpg
  - name: Amanda Ong
    position: Unarmed Team NCO
    img: sergeant.jpg

academicmembers:
  - name: Albert Gu
    position: Academic Team NCO
    img: commander.jpg
  - name: Alan Hang
    position: Academic Team NCO
    img: sergeant.jpg

kittyhawkmembers:
  - name: Clyde Rapiñan
    position: Kitty Hawk Officer
    img: commander.jpg
  - name: Athena Amanatidis
    position: Kitty Hawk NCO
    img: sergeant.jpg

staffmembers:
  - name: Valerie Ho
    position: Group Commander
    img: valerie.jpg
  - name: Brandon Nguyen
    position: Deputy Commander
    img: brandon.jpg
  - name: Chole Dietrich
    position: First Sergeant
    img: chole.jpg
  - name: Evan Dicker
    position: Operations Commander
    img: evan.jpg
  - name: Nick Stone
    position: Teams Commander
    img: nick.jpg
  - name: Shane Donahue
    position: Mission Support Commander
    img: shane.jpg
  - name: Lindsey Trinh
    position: Plans and Programs
    img: lindsey.jpg
  - name: Christine Nguyen
    position: Logistics Commander
    img: christine.jpg
  - name: Johanna Kye
    position: Public Affairs Commander
    img: johanna.jpg
    
ypfmembers:
  - name: TBA
    position: YPF Captain
    img: placeholder.jpg
  - name: TBA
    position: YPF Co-Captain
    img: placeholder.jpg

aptmembers:
  - name: Lynn Lu
    position: APT Commander
    img: commander.jpg
  - name: Lauren Kogelman
    position: APT NCO
    img: sergeant.jpg
    
cyberpatriotmembers:
  - name: Adrian Resubal
    position: CyberPatriot Commander
    img: commander.jpg
    
# Clients information. Shown on Home and About pages.
sponsors:
  - name: iD Tech
    img: sponsor1.svg

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Scripps Ranch High School’s Air Force Junior Reserve Officer Training Corps (AFJROTC) CA-935th program has been the number 
one JROTC unit in the San Diego Unified School District for many years. We value hard-work, friendship, and achievement, pushing our 
cadets not only to be their best, but also to perform their best."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "It's not what you have or what you know; it's what you do with your talent, skills, knowledge, and education that will determine your perfomance and give you the competitive edge!"
    author: MSgt. Toledo
    position: Aerospace Science Instructor - SRHS AFJROTC

prose:
  rooturl: '_posts'
  siteurl: 'https://ca-935.github.io'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "tag1"
              value: "tag1"
            - name: "tag2s"
              value: "tag2"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
